# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: conf.py   # Path to Sphinx’s main config file

python:
  install:
    - requirements: requirements.txt   # Install dependencies if listed here

formats:
  - pdf
  - epub
  - htmlzip
